spring:
  banner:
    location: banner.txt
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:.env[.properties]
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    hikari:
      initialization-fail-timeout: 10000
  liquibase:
    change-log: classpath:db/changelog/master.xml

server:
  port: ${PORT:80}
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: alpha
    persist-authorization: true

