version: "3.7"
services:

  backend:
    container_name: tolkien_backend
    depends_on:
      - database
    build:
      context: '..'
      dockerfile: docker/Dockerfile
    environment:
      DB_URL: jdbc:mariadb://database:3306/tolkien_api
      DB_USERNAME: api
      DB_PASSWORD: password
      DB_DRIVER: org.mariadb.jdbc.Driver
      PORT: 80
    networks:
      - backend
    ports:
      - "8080:80"

  database:
    container_name: tolkien_database
    image: mariadb:10.4
    environment:
      MYSQL_DATABASE: tolkien_api
      MYSQL_USER: api
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: changeme
    tty: true
    networks:
      - backend
    volumes:
      - database_volume:/var/lib/mariadb

networks:
  backend:

volumes:
  database_volume: